name: Deploy Contracts

on:
  workflow_dispatch:
    inputs:
      network:
        description: "Network to deploy to"
        required: true
        default: "avalancheFuji"
        type: choice
        options:
          - avalancheFuji
          - avalancheMainnet

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 12

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false

      - name: Deploy Contract
        env:
          PRIVATE_KEY: ${{ secrets.DEPLOYER_PRIVATE_KEY }}
          AVALANCHE_FUJI_RPC_URL: ${{ secrets.AVALANCHE_FUJI_RPC_URL }}
          AVALANCHE_MAINNET_RPC_URL: ${{ secrets.AVALANCHE_MAINNET_RPC_URL }}
        run: pnpm hardhat run scripts/deploy.ts --network ${{ inputs.network }}
